"""adicionado a tabela profissional

Revision ID: 523139a7967a
Revises: 0b9789995081
Create Date: 2025-05-16 23:29:11.922169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523139a7967a'
down_revision = '0b9789995081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profissional',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=True),
    sa.Column('crm', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profissional')
    # ### end Alembic commands ###
